### ISSUE TITLE
Shows always "You need to login to access this page!" on Dedi

### ISSUE THREAD

**Issue by TethysSaturn** [Xentro/FS19_GameExtension#13]
With the Version 0.6.1.0 I have the problem that GameExtension asks me to login as Admin on my dedicated server even when I'm already logged in as Admin. 

v.0.6.0.0 is working fine. As soon as I'm logged in as admin I can see all features

rgds

Tethys

**Comment by Xentro** [comment]
Had an quick look and indeed there were problems, hopefully it works now.
I'm leaving this open until someone else (other then me) confirmed it to be fixed.

**Comment by TethysSaturn** [comment]
v0.6.2.1 is working again on Dedi, Thx for the fast fix
