### ISSUE TITLE
The trailer can not be unloaded

### ISSUE THREAD

**Issue by KITT3000** [Xentro/FS19_GameExtension#14]
When you try to unload a silo trailer instead of unloading, the mod menu appears.

**Comment by Xentro** [comment]
I have been thinking on an new key to press to avoid this issue and the key Im thinking on is
left alt + q
Its simple to press and dont conflict with default, feedback on that is welcomed.
I will push this update when I sorted some more input stuff.

**Comment by Xentro** [comment]
Invalid since e506dad
