### ISSUE TITLE
[Sugestion] Hide chat and names of players in MP

### ISSUE THREAD

**Issue by KITT3000** [Xentro/FS19_GameExtension#4]
I miss hiding chat in MP mode very much. When I want to record something from our game, this chat often disturbs me, similarly with the players' nicks. Would you be able to add such an option? It is important that it is on the client's side and not the server because of this, so that everyone can change these two options according to their own will.

**Comment by Xentro** [comment]
These features have been added to 48b2fd7
I have only done a rough test of them, if anyone has the opportunity to test in an actual game and report back if it works as should that would be much appreciated.
I will close this once its been confirmed to work.

**Comment by KITT3000** [comment]
The function with nicknames of players works correctly. Unfortunately, chat does not work when anyone writes his (host) entries all the time, only me (client) can not write anything after turning on "hide chat", but the chat button still appears in the help window and if the chat disappears automatically it appears again at the press of a button.

In addition, such an error appeared:
```
2019-01-27 20:20 Error: Running LUA method 'mouseEvent'.
2019-01-27 20:20 mods/moje/FS19_GameExtension/scripts/modules/Misc.lua:40: bad argument #1 to 'ipairs' (table expected, got nil)
```
when the host did not accept my joining the server and I clicked the "Cancel" button.

**Comment by Xentro** [comment]
Lua error have been fixed.
Button is being deactivated when setting is set to hide have also been added as for the messages showing when someone else writes an message will come later this week hopefully.

**Comment by Xentro** [comment]
37b1539
This is ready for another test, should be working allot better this time xD

**Comment by KITT3000** [comment]
I tested and now everything works correctly. I did not check the dedicated server only.
